{% set version = "0.7.27" %}
{% set name = "pynac" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/pynac/pynac/releases/download/pynac-{{ version }}/pynac-{{ version }}.tar.bz2
  sha256: 0ca3f7fcfdf46a2f63e414bd516b501d747c79201279e26aa99e03df5efedd4d

build:
  number: 1
  skip: true  # [win]
  skip: true  # [py3k and py<36]

requirements:
  build:
    - {{ compiler('cxx') }}
    - libtool
    - make
  host:
    - pkg-config
    - python
    - gmp
    - mpfr
    - libflint
    - singular 4.1.1
    - ntl
  run:
    - python
    - gmp
    - mpfr
    - libflint
    - singular
    - ntl
  run_constrained:
    - sagelib >8.9

test:
  commands:
    - test -f ${PREFIX}/include/pynac/ginac.h
    - test -f ${PREFIX}/lib/lib{{ name }}.dylib     # [osx]
    - test -f ${PREFIX}/lib/lib{{ name }}.so        # [linux]

about:
  home: http://pynac.org/
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: SageMath support library for symbolic computations
  dev_url: https://github.com/pynac/pynac

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
