{% set version = "0.7.25" %}
{% set name = "pynac" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.bz2
  url: https://github.com/pynac/pynac/releases/download/pynac-{{ version }}/pynac-{{ version }}.tar.bz2
  sha256: db12bc1ec2f3a34d8ca9c677c8da747112e9b6b819512c110a6209026e2efcd6

build:
  number: 3
  skip: true  # [win]
  skip: true  # [py3k and py<36]

requirements:
  build:
    - {{ compiler('cxx') }}
    - libtool
  host:
    - pkg-config
    - python
    - gmp
    - mpfr
    - libflint 2.5.*
    - singular
  run:
    - python
    - gmp
    - mpfr
    - libflint
    - singular

test:
  commands:
    - test -f ${PREFIX}/include/pynac/ginac.h
    - test -f ${PREFIX}/lib/lib{{ name }}.a
    - test -f ${PREFIX}/lib/lib{{ name }}.dylib     # [osx]
    - test -f ${PREFIX}/lib/lib{{ name }}.so        # [linux]

about:
  home: http://pynac.org/
  license: GPLv2+
  license_file: COPYING
  summary: SageMath support library for symbolic computations
  dev_url: https://github.com/pynac/pynac

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
