{% set version = "0.7.28" %}
{% set name = "pynac" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/pynac/pynac/releases/download/pynac-{{ version }}/pynac-{{ version }}.tar.bz2
  sha256: 7ff46622fd366f4015e730a89e281ee40502a771f45df34c6c65114526f664fd
  patches:
    # patches taken from sage
    - patches/disable_poly_mul_expand.patch
    - patches/handle_factor.patch
    - patches/power_inf_loop.patch
    - patches/seriesbug.patch
    - patches/too_much_sub.patch

build:
  number: 0
  skip: true  # [win]
  skip: true  # [py3k and py<36]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - gnuconfig  # [unix]
    - {{ compiler('cxx') }}
    - libtool
    - make
    - pkg-config
  host:
    - python
    - gmp
    - mpfr
    - libflint
    - singular
    - ntl
  run:
    - python
    - gmp
    - mpfr
    - libflint
    - singular
    - ntl
  run_constrained:
    - sagelib >8.9

test:
  commands:
    - test -f ${PREFIX}/include/pynac/ginac.h
    - test -f ${PREFIX}/lib/lib{{ name }}.dylib     # [osx]
    - test -f ${PREFIX}/lib/lib{{ name }}.so        # [linux]

about:
  home: http://pynac.org/
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: SageMath support library for symbolic computations
  dev_url: https://github.com/pynac/pynac

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
