# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Kyy5Wu/gBh/hkcdISiwHi3/UkPhgwVMWuU9bJ0rlK8mP36PSmlm/+CNfmbtqyElxdBNIUuu2dX8TqZnk5M8r6kTTkoEXxT8Rd/c9hzoPkC3AX1PSVaZG9sMPkyyHpFoWGuHbuAzXuBLPNtXuK5qSnDNTXlE3xpHcdMBaQ4VyVLdRLNLGzlBw60WgPMGk2Va3sg+h4JDpWki9s4uYwYJj15CYMHMJQifto67gf+Ox7k6jA7PZnIFGjFEnunFqqVnlJJ9G+oDXe8aiCsk4S+ro9NRatQCbB0xQ8tcG7uWjZtcoIxBFBaNyn4ZSnHPxhAaEe3dpsOJ/V38LrCfdXPlVjGuiDFRVSjdeL0fFxoH/FvHGlohurLEtAxvs9Mo07p2KiByBE+8gOLdFVyOGd5/HokYob8zDZtjjer2SrQiVoHXz0lUOe6l5fHAiTNq5G0yuj0J+ZAWWP5gigdX1EqQkOFcdGXzMZ4LL1KJwKCdIbPcSEmhwK0aR5+eV4cW/tksKL6C0D4zVnXsbZlN1iv0k1Q6M7MjkfbT+C0oUEKUp0mn1fHjv/zRQCsnF4DR7DiF9+50AT3FWvZrdMBrIEkH1eh0jBrsKKUV9jgBevXdJUWtROFVQY1TQ5xID4Rhxqth+yHRRy3qWUYnIbGc5cv00BmHbjPt6znUBxSFxWB+7Bdc="


before_install:
    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
