travis:
  secure:
    BINSTAR_TOKEN: Gp7p5yc+wjxLy+RnOMX/TrTXjxD/VpjCUq0imV+4J5ADX6O1xqxhWb4/SFoy3sILvNXBsMB8H3cu0td87KN5OABFQ3iowdaGYvgivZjVKTW7RVufy3O8kjmrRIkCh9BCOPnCF+bDmdc1HTWeBjEBxW93lsYi7MR2XnXCaIxBhDAakzESc81wleEDoa1j0zARDCakZAvwX1X7eFERMzsHJSRgjTou44TjIIPmnhsyjMxr4u0TLQdZfqS09hsz4KERBJmPOD3swRvZVqjF7L1k3SjjWLJfsuTXwYfBjKFbGxSRMUVQeuGG+PU56FsujVdcCcQyr1UQuhOBHdjIkT4HFkP7p1WHTVfp71vgdmYADZ4JUSozZYCb/v5yRARuuQ0AMvuEWWT2mSNxrk1/oAEb/NmoukAq6MHCuP5ccOFHoZ1lH/ElbymWDBoSozQUOcrTkjt0TrZT1PF59slFDYbAvoi7wfTigL6AIy6KJmAu/FmykQLAGg8nBrgAfs/Mziyl7dVgeenqGdH7z+VDK+Iw4LnZ/6iJjKGzi6eqfFFDBOJ06DbCcuwiRs+b5QtJBuJQBcDIXBhB8ZlZCsgjjV25FtAt2V4AJGwnGHnZ2izUnofXOA3h33kMnFlzAXG60R3qEvaZMLAG39H9K3v9wm3K+hJbJLFh0fSOnwRGc4P8h/s=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
