travis:
  secure:
    BINSTAR_TOKEN: PRRUsIpPRa8nav2qmwCVA0Erw5hjLSYlPKaIudfp9Kzn+EGw17KsdQJx6tdIvPVdVQnZajsFwUMEhB9LevMmj/JT6HEsNe773pJhYKnN54yzQn6dkbPq5irbOoSc3IfcdxuUBzrtpDhXN7RYuMYvWlZIYbsnA8Zfvdu1cGGqq1R2Hfx6t6jbt7HqvO5YiQV7Gdum6F/n66EGhUfj8l16c3MNLdXgW5xp8j2MS+boVT1mnQ3O7mmFsKsSZ6/hMka3gqK9w7zjjxWkZFrh4RT0liAt9H4DqzAET7ogWeVjvPGC5za7X2tKgfokq57xHIR/dwatuJkY0zMN1RqPewEtCy/vi5IPfuGnG6eI2g9b8YokwRJCCh6WD/XEcag68SNrI5LWUwC8Sh1iOjDAPBDHRcVKXLXoDYbtZtVDZnVvZ8bUheNi5UnTrrYj7FEE1flAigdkLt8fvm7GHYMMWwn8JiBLJGR3jcHZuDnW/gfQ0shQo7enqK06GLmMx5XTFz/tCf8Ui25z39vSAgLF8nvkghLJkcYo0dRmZGmqfuV9ouNI7+BgjaI6nYgPAk64+X1bqPC+C0RPq6NMm2k+dm/cSWtQ4YaWHzO2fTaEG89uiULqwcRg2iR2tekH0H5zJ+KGgCq+n2B3XK0IsHbHmLWnP+rnjP5ezto1k8sM47/eaw4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
conda_forge_output_validation: true
